# Generated by Django 5.2.15 on 2026-06-08 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_identifier', models.CharField(blank=True, max_length=255, verbose_name='admin identifier')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_index=True, max_length=10, verbose_name='action type')),
                ('model_name', models.CharField(db_index=True, max_length=120, verbose_name='model name')),
                ('object_id', models.CharField(db_index=True, max_length=64, verbose_name='object id')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='object representation')),
                ('changes_json', models.JSONField(blank=True, default=dict, help_text="Field-level diff: {field: {'old': ..., 'new': ...}}. For creates the 'old' values are null; for deletes the 'new' values are null.", verbose_name='changes')),
                ('source', models.CharField(default='admin', help_text="Where the change originated: 'admin', 'api', 'system'.", max_length=20, verbose_name='source')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='admin user')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='analytics_a_model_n_cbae55_idx'), models.Index(fields=['admin_user', 'timestamp'], name='analytics_a_admin_u_4dfb71_idx'), models.Index(fields=['action_type', 'timestamp'], name='analytics_a_action__0d048f_idx')],
            },
        ),
    ]
