# Generated by Django 5.2.15 on 2026-06-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_identifier', models.CharField(blank=True, max_length=255, verbose_name='admin identifier')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_index=True, max_length=10, verbose_name='action type')),
                ('model_name', models.CharField(db_index=True, max_length=120, verbose_name='model name')),
                ('object_id', models.CharField(db_index=True, max_length=64, verbose_name='object id')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='object representation')),
                ('changes_json', models.JSONField(blank=True, default=dict, help_text="Field-level diff: {field: {'old': ..., 'new': ...}}. For creates the 'old' values are null; for deletes the 'new' values are null.", verbose_name='changes')),
                ('source', models.CharField(default='admin', help_text="Where the change originated: 'admin', 'api', 'system'.", max_length=20, verbose_name='source')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ('-timestamp',),
            },
        ),
    ]
