# Generated by Django 5.2.15 on 2026-06-10 09:40

import apps.authentication.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(help_text='شناسه\u200cی اصلی ورود و احراز هویت.', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تماس معتبر وارد کنید (۹ تا ۱۵ رقم، با + اختیاری). مثال: +989121234567', regex='^\\+?\\d{9,15}$')], verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, help_text='اختیاری؛ در صورت ورود باید یکتا باشد.', max_length=254, null=True, unique=True, verbose_name='ایمیل')),
                ('role', models.CharField(choices=[('OWNER', 'مالک'), ('ADMIN', 'مدیر'), ('CUSTOMER', 'مشتری')], db_index=True, default='CUSTOMER', max_length=10, verbose_name='نقش')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='شماره تأییدشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.authentication.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, verbose_name='هش کد')),
                ('purpose', models.CharField(choices=[('LOGIN', 'ورود'), ('REGISTER', 'ثبت\u200cنام'), ('RESET', 'بازیابی')], default='LOGIN', max_length=10, verbose_name='هدف')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده\u200cشده')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='حداکثر تلاش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کد یک\u200cبارمصرف',
                'verbose_name_plural': 'کدهای یک\u200cبارمصرف',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='authenticat_user_id_46c382_idx')],
            },
        ),
    ]
