# Generated by Django 5.2.15 on 2026-06-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productreview_created_at_and_more'),
        ('catalog', '0003_wishlistitem'),
    ]

    operations = [
    ]
