# Generated by Django 5.2.15 on 2026-06-11 18:34

import apps.catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_wishlistitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/brands/', validators=[apps.catalog.validators.SecureCatalogImageValidator()], verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/categories/icons/', validators=[apps.catalog.validators.SecureCatalogImageValidator()], verbose_name='آیکن'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/categories/images/', validators=[apps.catalog.validators.SecureCatalogImageValidator()], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='catalog/products/', validators=[apps.catalog.validators.SecureCatalogImageValidator()], verbose_name='تصویر'),
        ),
    ]
